[package]
name = "rust-wasm-spa"
version = "0.1.0"
authors = ["lonnen <chris.lonnen@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2"