[package]
name = "rust-wasm-spa"
version = "0.1.0"
authors = ["lonnen <chris.lonnen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
